/* Generated By:JavaCC: Do not edit this line. TableGenParserConstants.java */
package com.rtrk.netbeansllvmsdk.td.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TableGenParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int BIT = 4;
  /** RegularExpression Id. */
  int BITS = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int CODE = 7;
  /** RegularExpression Id. */
  int DAG = 8;
  /** RegularExpression Id. */
  int DEF = 9;
  /** RegularExpression Id. */
  int FOREACH = 10;
  /** RegularExpression Id. */
  int DEFM = 11;
  /** RegularExpression Id. */
  int FIELD = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int LET = 15;
  /** RegularExpression Id. */
  int LIST = 16;
  /** RegularExpression Id. */
  int MULTICLASS = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 19;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 20;
  /** RegularExpression Id. */
  int HEX_LITERAL = 21;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 22;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 23;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 24;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 25;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 26;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 27;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 28;
  /** RegularExpression Id. */
  int STRING_LITERAL = 29;
  /** RegularExpression Id. */
  int IDENTIFIER = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int PART_LETTER = 32;
  /** RegularExpression Id. */
  int LPAREN = 33;
  /** RegularExpression Id. */
  int RPAREN = 34;
  /** RegularExpression Id. */
  int LBRACE = 35;
  /** RegularExpression Id. */
  int RBRACE = 36;
  /** RegularExpression Id. */
  int LBRACKET = 37;
  /** RegularExpression Id. */
  int RBRACKET = 38;
  /** RegularExpression Id. */
  int SEMICOLON = 39;
  /** RegularExpression Id. */
  int COMMA = 40;
  /** RegularExpression Id. */
  int DOT = 41;
  /** RegularExpression Id. */
  int ASSIGN = 42;
  /** RegularExpression Id. */
  int EQ = 43;
  /** RegularExpression Id. */
  int LE = 44;
  /** RegularExpression Id. */
  int GE = 45;
  /** RegularExpression Id. */
  int SC_OR = 46;
  /** RegularExpression Id. */
  int SC_AND = 47;
  /** RegularExpression Id. */
  int LT = 48;
  /** RegularExpression Id. */
  int GT = 49;
  /** RegularExpression Id. */
  int BANG = 50;
  /** RegularExpression Id. */
  int HOOK = 51;
  /** RegularExpression Id. */
  int COLON = 52;
  /** RegularExpression Id. */
  int PLUS = 53;
  /** RegularExpression Id. */
  int MINUS = 54;
  /** RegularExpression Id. */
  int STAR = 55;
  /** RegularExpression Id. */
  int SLASH = 56;
  /** RegularExpression Id. */
  int REM = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"bit\"",
    "\"bits\"",
    "\"class\"",
    "\"code\"",
    "\"dag\"",
    "\"def\"",
    "\"foreach\"",
    "\"defm\"",
    "\"field\"",
    "\"in\"",
    "\"int\"",
    "\"let\"",
    "\"list\"",
    "\"multiclass\"",
    "\"string\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"?\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
