/* Generated By:JavaCC: Do not edit this line. TableGenParserConstants.java */
package com.rtrk.netbeansllvmsdk.td.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TableGenParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int BIT = 12;
  /** RegularExpression Id. */
  int BITS = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int CODE = 15;
  /** RegularExpression Id. */
  int DAG = 16;
  /** RegularExpression Id. */
  int DEF = 17;
  /** RegularExpression Id. */
  int FOREACH = 18;
  /** RegularExpression Id. */
  int DEFM = 19;
  /** RegularExpression Id. */
  int FIELD = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int LET = 23;
  /** RegularExpression Id. */
  int LIST = 24;
  /** RegularExpression Id. */
  int MULTICLASS = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 27;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 28;
  /** RegularExpression Id. */
  int HEX_LITERAL = 29;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 30;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 31;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 32;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 33;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 34;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 35;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 36;
  /** RegularExpression Id. */
  int STRING_LITERAL = 37;
  /** RegularExpression Id. */
  int IDENTIFIER = 38;
  /** RegularExpression Id. */
  int LETTER = 39;
  /** RegularExpression Id. */
  int PART_LETTER = 40;
  /** RegularExpression Id. */
  int LPAREN = 41;
  /** RegularExpression Id. */
  int RPAREN = 42;
  /** RegularExpression Id. */
  int LBRACE = 43;
  /** RegularExpression Id. */
  int RBRACE = 44;
  /** RegularExpression Id. */
  int LBRACKET = 45;
  /** RegularExpression Id. */
  int RBRACKET = 46;
  /** RegularExpression Id. */
  int SEMICOLON = 47;
  /** RegularExpression Id. */
  int COMMA = 48;
  /** RegularExpression Id. */
  int DOT = 49;
  /** RegularExpression Id. */
  int AT = 50;
  /** RegularExpression Id. */
  int ASSIGN = 51;
  /** RegularExpression Id. */
  int LT = 52;
  /** RegularExpression Id. */
  int BANG = 53;
  /** RegularExpression Id. */
  int TILDE = 54;
  /** RegularExpression Id. */
  int HOOK = 55;
  /** RegularExpression Id. */
  int COLON = 56;
  /** RegularExpression Id. */
  int EQ = 57;
  /** RegularExpression Id. */
  int LE = 58;
  /** RegularExpression Id. */
  int GE = 59;
  /** RegularExpression Id. */
  int NE = 60;
  /** RegularExpression Id. */
  int SC_OR = 61;
  /** RegularExpression Id. */
  int SC_AND = 62;
  /** RegularExpression Id. */
  int INCR = 63;
  /** RegularExpression Id. */
  int DECR = 64;
  /** RegularExpression Id. */
  int PLUS = 65;
  /** RegularExpression Id. */
  int MINUS = 66;
  /** RegularExpression Id. */
  int STAR = 67;
  /** RegularExpression Id. */
  int SLASH = 68;
  /** RegularExpression Id. */
  int BIT_AND = 69;
  /** RegularExpression Id. */
  int BIT_OR = 70;
  /** RegularExpression Id. */
  int XOR = 71;
  /** RegularExpression Id. */
  int REM = 72;
  /** RegularExpression Id. */
  int LSHIFT = 73;
  /** RegularExpression Id. */
  int PLUSASSIGN = 74;
  /** RegularExpression Id. */
  int MINUSASSIGN = 75;
  /** RegularExpression Id. */
  int STARASSIGN = 76;
  /** RegularExpression Id. */
  int SLASHASSIGN = 77;
  /** RegularExpression Id. */
  int ANDASSIGN = 78;
  /** RegularExpression Id. */
  int ORASSIGN = 79;
  /** RegularExpression Id. */
  int XORASSIGN = 80;
  /** RegularExpression Id. */
  int REMASSIGN = 81;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 82;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 83;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 84;
  /** RegularExpression Id. */
  int ELLIPSIS = 85;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 86;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 87;
  /** RegularExpression Id. */
  int GT = 88;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"bit\"",
    "\"bits\"",
    "\"class\"",
    "\"code\"",
    "\"dag\"",
    "\"def\"",
    "\"foreach\"",
    "\"defm\"",
    "\"field\"",
    "\"in\"",
    "\"int\"",
    "\"let\"",
    "\"list\"",
    "\"multiclass\"",
    "\"string\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
